### ISSUE TITLE
[Heroku][AWS] handler not working because of url param rewritten

### ISSUE THREAD

**Issue by ylecuyer** [grokify/chathooks#13]
Hi, I tried to connect heroku to glip with the heroku deploy hooks addon but it is not working.

Heroku sends an URL param in the post body which overwrite the URL in the query.

Could we add an alias for the url param?

**Comment by ylecuyer** [comment]
I checked with the proxy running locally and this error is only for the aws handler.
Looks like the aws api gateway is the cause of this error.

**Comment by grokify** [comment]
I started looking into this and found that Heroku has updated their webhooks to use `application/json` from `application/x-www-form-urlencoded`.

https://devcenter.heroku.com/articles/app-webhooks#receiving-webhooks

This is noted as:

`"version": "application/vnd.heroku+json; version=3"`

I'll update to support the JSON webhook event format which should resolve this.

**Comment by grokify** [comment]
Here's some info on potentially overloading `text/plain` Content Type:

* https://stackoverflow.com/questions/31362195/output-plain-text-content-from-amazon-api-gateway-endpoint
* https://www.reddit.com/r/aws/comments/6219kx/api_gateway_non_json_inputs_textplain/

**Comment by grokify** [comment]
Implemented in a3b406c3562b200f9c36c75e6de1c0a5c02c5441

As of this commit, `url` param has been renamed to `outputURL` param. There is no fallback but multiple instances of Chathooks can be run during the roll over.

**Comment by grokify** [comment]
v0.7.0 Released.
